#!/usr/bin/env bash
# Writes ios/Flutter/DartDefines.xcconfig, the iOS half of ADR-0015: the bundle id suffix, the
# display name and the App Links host come from the same define file as the Dart code.
#
#   tool/write_ios_defines.sh config/env/prod.json   # from a define file (release workflow)
#   tool/write_ios_defines.sh                        # from $DART_DEFINES (Xcode pre-action)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/../ios/Flutter/DartDefines.xcconfig"

emit() { # key value
  case "$1" in
    APP_NAME) echo "APP_DISPLAY_NAME = $2" ;;
    APP_LINK_HOST) echo "APP_LINK_HOST = $2" ;;
    APP_FLAVOR) if [ "$2" = prod ]; then echo "APP_ID_SUFFIX ="; else echo "APP_ID_SUFFIX = .$2"; fi ;;
  esac
}

{
  echo "// Generated by tool/write_ios_defines.sh. Do not edit; do not commit."
  if [ $# -ge 1 ]; then
    python3 - "$1" <<'PY' | while IFS=$'\t' read -r key value; do emit "$key" "$value"; done
import json, sys
for key, value in json.load(open(sys.argv[1])).items():
    print(f"{key}\t{value}")
PY
  else
    IFS=',' read -r -a encoded <<< "${DART_DEFINES:-}"
    for item in "${encoded[@]}"; do
      [ -n "$item" ] || continue
      pair="$(printf '%s' "$item" | base64 --decode)"
      emit "${pair%%=*}" "${pair#*=}"
    done
  fi
} > "$out"
echo "wrote $out"
