#!/usr/bin/env node
// Generates tokens.css (CSS custom properties) from tokens.json, so the web
// apps switch brand colors with the colour scheme exactly as the Flutter
// themes do. Dark-first: the dark values are the defaults and light applies
// under `prefers-color-scheme: light`.
//
//   node packages/design-tokens/build-css.mjs          # write
//   node packages/design-tokens/build-css.mjs --check  # fail if stale (CI)
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));
const c = tokens.color;

const rgb = (hex) => {
  const h = hex.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16)).join(' ');
};

function vars(theme) {
  const brand = theme === 'dark' ? c.brand.dark : c.brand;
  const surface = c.surface[theme];
  const gradient = c.brand.gradient[theme];
  return [
    `--sk-brand-primary: ${rgb(brand.primary)};`,
    `--sk-brand-primary-strong: ${rgb(brand.primaryStrong)};`,
    `--sk-brand-on-primary: ${rgb(brand.onPrimary)};`,
    `--sk-brand-secondary: ${rgb(brand.secondary)};`,
    `--sk-brand-on-secondary: ${rgb(brand.onSecondary)};`,
    `--sk-gradient: linear-gradient(135deg, ${gradient.join(', ')});`,
    `--sk-on-gradient: ${c.brand.onGradient[theme]};`,
    `--sk-background: ${surface.background};`,
    `--sk-glass: ${surface.glass};`,
    `--sk-glass-border: ${surface.glassBorder};`,
    `--sk-blur-glass: ${tokens.blur.glass}px;`,
  ]
    .map((line) => `  ${line}`)
    .join('\n');
}

const css = `/* Generated by build-css.mjs from tokens.json — do not edit by hand. */
:root {
  color-scheme: dark light;
${vars('dark')}
}

@media (prefers-color-scheme: light) {
  :root {
${vars('light')
  .split('\n')
  .map((l) => `  ${l}`)
  .join('\n')}
  }
}

.sk-glass {
  background: var(--sk-glass);
  border: 1px solid var(--sk-glass-border);
  -webkit-backdrop-filter: blur(var(--sk-blur-glass)) saturate(1.4);
  backdrop-filter: blur(var(--sk-blur-glass)) saturate(1.4);
}

.sk-gradient {
  background-image: var(--sk-gradient);
  color: var(--sk-on-gradient);
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }
}
`;

const out = join(here, 'tokens.css');
if (process.argv.includes('--check')) {
  const current = readFileSync(out, 'utf8');
  if (current !== css) {
    console.error('tokens.css is stale: run node packages/design-tokens/build-css.mjs');
    process.exit(1);
  }
  console.log('tokens.css is up to date');
} else {
  writeFileSync(out, css);
  console.log(`wrote ${out}`);
}
