#!/usr/bin/env bash
# Appends a [remotes.deploy] block to supabase/config.toml for the project being deployed, so
# `supabase config push` sends that project's own values instead of the local-stack defaults
# (hook URL on host.docker.internal, 127.0.0.1 site URL, CAPTCHA off).
#
# The block is generated in CI rather than committed because the CLI rejects a remote whose
# project_id is not a real 20-letter project ref, which would break every local `supabase start`.
#
# Required env: SUPABASE_PROJECT_REF, SITE_URL
# Optional env: ADDITIONAL_REDIRECT_URLS (comma-separated), SUPABASE_AUTH_CAPTCHA_SECRET,
#   GOOGLE_CLIENT_IDS (comma-separated, web client first), GOOGLE_SKIP_NONCE_CHECK (true when an
#   iOS client ID is listed), SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET (web OAuth only),
#   APPLE_CLIENT_IDS (comma-separated bundle IDs, plus the Services ID for web),
#   SUPABASE_AUTH_EXTERNAL_APPLE_SECRET (web OAuth only)
# Native sign-in (signInWithIdToken) needs only the client IDs; secrets are for the web OAuth
# flow (supabase.com/docs/guides/auth/social-login/auth-google and auth-apple, checked 2026-09-17).
# Secrets referenced (resolved by the CLI from the environment at push time):
#   SEND_SMS_HOOK_SECRETS, SUPABASE_AUTH_CAPTCHA_SECRET, SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET,
#   SUPABASE_AUTH_EXTERNAL_APPLE_SECRET
set -euo pipefail

CONFIG="${1:-supabase/config.toml}"
: "${SUPABASE_PROJECT_REF:?SUPABASE_PROJECT_REF is required}"
: "${SITE_URL:?SITE_URL is required}"

if ! [[ "$SUPABASE_PROJECT_REF" =~ ^[a-z]{20}$ ]]; then
  echo "SUPABASE_PROJECT_REF must be a 20-letter project ref" >&2
  exit 1
fi
if ! [[ "$SITE_URL" =~ ^https:// ]]; then
  echo "SITE_URL must be https" >&2
  exit 1
fi
if grep -q '^\[remotes\.deploy\]' "$CONFIG"; then
  echo "[remotes.deploy] already present in $CONFIG" >&2
  exit 1
fi

if [ -n "${GOOGLE_CLIENT_IDS:-}" ] &&
   ! [[ "$GOOGLE_CLIENT_IDS" =~ ^[A-Za-z0-9-]+\.apps\.googleusercontent\.com(,[A-Za-z0-9-]+\.apps\.googleusercontent\.com)*$ ]]; then
  echo "GOOGLE_CLIENT_IDS must be comma-separated *.apps.googleusercontent.com client IDs, web first" >&2
  exit 1
fi
if [ -n "${GOOGLE_SKIP_NONCE_CHECK:-}" ] && ! [[ "$GOOGLE_SKIP_NONCE_CHECK" =~ ^(true|false)$ ]]; then
  echo "GOOGLE_SKIP_NONCE_CHECK must be true or false" >&2
  exit 1
fi
if [ -n "${APPLE_CLIENT_IDS:-}" ] && ! [[ "$APPLE_CLIENT_IDS" =~ ^[A-Za-z0-9.-]+(,[A-Za-z0-9.-]+)*$ ]]; then
  echo "APPLE_CLIENT_IDS must be comma-separated bundle or Services IDs" >&2
  exit 1
fi
if [ -n "${GOOGLE_CLIENT_IDS:-}" ] && [ -z "${APPLE_CLIENT_IDS:-}" ]; then
  # Spec platform rule: Sign in with Apple wherever Google sign-in is offered.
  echo "::warning::Google sign-in is enabled without Sign in with Apple (spec platform rule for iOS)"
fi

no_toml_breakers='^[^"\\[:space:]]+$'
if [ -n "${ADDITIONAL_REDIRECT_URLS:-}" ] && ! [[ "$ADDITIONAL_REDIRECT_URLS" =~ $no_toml_breakers ]]; then
  echo "ADDITIONAL_REDIRECT_URLS must be comma-separated URLs without quotes or spaces" >&2
  exit 1
fi

redirects="[]"
if [ -n "${ADDITIONAL_REDIRECT_URLS:-}" ]; then
  redirects="[$(printf '%s' "$ADDITIONAL_REDIRECT_URLS" | awk -F',' '{for (i = 1; i <= NF; i++) printf "%s\"%s\"", (i > 1 ? ", " : ""), $i}')]"
fi

{
  echo ""
  echo "# ---- generated by supabase/deploy/write-remote-config.sh; never committed ----"
  echo "[remotes.deploy]"
  echo "project_id = \"$SUPABASE_PROJECT_REF\""
  echo ""
  echo "[remotes.deploy.auth]"
  echo "site_url = \"$SITE_URL\""
  echo "additional_redirect_urls = $redirects"
  echo ""
  echo "[remotes.deploy.auth.hook.send_sms]"
  echo "enabled = true"
  echo "uri = \"https://$SUPABASE_PROJECT_REF.supabase.co/functions/v1/auth-send-sms\""
  echo "secrets = \"env(SEND_SMS_HOOK_SECRETS)\""
  if [ -n "${SUPABASE_AUTH_CAPTCHA_SECRET:-}" ]; then
    echo ""
    echo "[remotes.deploy.auth.captcha]"
    echo "enabled = true"
    echo "provider = \"turnstile\""
    echo "secret = \"env(SUPABASE_AUTH_CAPTCHA_SECRET)\""
  fi
  if [ -n "${GOOGLE_CLIENT_IDS:-}" ]; then
    echo ""
    echo "[remotes.deploy.auth.external.google]"
    echo "enabled = true"
    echo "client_id = \"$GOOGLE_CLIENT_IDS\""
    echo "skip_nonce_check = ${GOOGLE_SKIP_NONCE_CHECK:-false}"
    if [ -n "${SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET:-}" ]; then
      echo "secret = \"env(SUPABASE_AUTH_EXTERNAL_GOOGLE_SECRET)\""
    fi
  fi
  if [ -n "${APPLE_CLIENT_IDS:-}" ]; then
    echo ""
    echo "[remotes.deploy.auth.external.apple]"
    echo "enabled = true"
    echo "client_id = \"$APPLE_CLIENT_IDS\""
    if [ -n "${SUPABASE_AUTH_EXTERNAL_APPLE_SECRET:-}" ]; then
      echo "secret = \"env(SUPABASE_AUTH_EXTERNAL_APPLE_SECRET)\""
    fi
  fi
} >> "$CONFIG"

echo "Wrote [remotes.deploy] for project $SUPABASE_PROJECT_REF"
