#!/usr/bin/env bash
# Appends a [remotes.deploy] block to supabase/config.toml for the project being deployed, so
# `supabase config push` sends that project's own values instead of the local-stack defaults
# (hook URL on host.docker.internal, 127.0.0.1 site URL, CAPTCHA off).
#
# The block is generated in CI rather than committed because the CLI rejects a remote whose
# project_id is not a real 20-letter project ref, which would break every local `supabase start`.
#
# Required env: SUPABASE_PROJECT_REF, SITE_URL
# Optional env: ADDITIONAL_REDIRECT_URLS (comma-separated), SUPABASE_AUTH_CAPTCHA_SECRET
# Secrets referenced (resolved by the CLI from the environment at push time):
#   SEND_SMS_HOOK_SECRETS, SUPABASE_AUTH_CAPTCHA_SECRET
set -euo pipefail

CONFIG="${1:-supabase/config.toml}"
: "${SUPABASE_PROJECT_REF:?SUPABASE_PROJECT_REF is required}"
: "${SITE_URL:?SITE_URL is required}"

if ! [[ "$SUPABASE_PROJECT_REF" =~ ^[a-z]{20}$ ]]; then
  echo "SUPABASE_PROJECT_REF must be a 20-letter project ref" >&2
  exit 1
fi
if ! [[ "$SITE_URL" =~ ^https:// ]]; then
  echo "SITE_URL must be https" >&2
  exit 1
fi
if grep -q '^\[remotes\.deploy\]' "$CONFIG"; then
  echo "[remotes.deploy] already present in $CONFIG" >&2
  exit 1
fi

redirects="[]"
if [ -n "${ADDITIONAL_REDIRECT_URLS:-}" ]; then
  redirects="[$(printf '%s' "$ADDITIONAL_REDIRECT_URLS" | awk -F',' '{for (i = 1; i <= NF; i++) printf "%s\"%s\"", (i > 1 ? ", " : ""), $i}')]"
fi

{
  echo ""
  echo "# ---- generated by supabase/deploy/write-remote-config.sh; never committed ----"
  echo "[remotes.deploy]"
  echo "project_id = \"$SUPABASE_PROJECT_REF\""
  echo ""
  echo "[remotes.deploy.auth]"
  echo "site_url = \"$SITE_URL\""
  echo "additional_redirect_urls = $redirects"
  echo ""
  echo "[remotes.deploy.auth.hook.send_sms]"
  echo "enabled = true"
  echo "uri = \"https://$SUPABASE_PROJECT_REF.supabase.co/functions/v1/auth-send-sms\""
  echo "secrets = \"env(SEND_SMS_HOOK_SECRETS)\""
  if [ -n "${SUPABASE_AUTH_CAPTCHA_SECRET:-}" ]; then
    echo ""
    echo "[remotes.deploy.auth.captcha]"
    echo "enabled = true"
    echo "provider = \"turnstile\""
    echo "secret = \"env(SUPABASE_AUTH_CAPTCHA_SECRET)\""
  fi
} >> "$CONFIG"

echo "Wrote [remotes.deploy] for project $SUPABASE_PROJECT_REF"
